/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthorizedRouteRouteImport } from './routes/_authorized/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorizedProfileRouteImport } from './routes/_authorized/profile'
import { Route as AuthorizedFeedbacksRouteImport } from './routes/_authorized/feedbacks'
import { Route as AuthorizedChatsRouteImport } from './routes/_authorized/chats'
import { Route as UnauthorizedUserRouteRouteImport } from './routes/_unauthorized/_user/route'
import { Route as UnauthorizedCompanyRouteRouteImport } from './routes/_unauthorized/_company/route'
import { Route as AuthorizedOfficesRouteRouteImport } from './routes/_authorized/offices/route'
import { Route as AuthorizedEditorRouteRouteImport } from './routes/_authorized/_editor/route'
import { Route as AuthorizedCompanyAdminRouteRouteImport } from './routes/_authorized/_companyAdmin/route'
import { Route as AuthorizedAdminRouteRouteImport } from './routes/_authorized/_admin/route'
import { Route as AuthorizedOfficesIndexRouteImport } from './routes/_authorized/offices/index'
import { Route as UnauthorizedUserLoginRouteImport } from './routes/_unauthorized/_user/login'
import { Route as UnauthorizedUserForgotPasswordRouteImport } from './routes/_unauthorized/_user/forgot-password'
import { Route as UnauthorizedUserCheckEmailRouteImport } from './routes/_unauthorized/_user/check-email'
import { Route as AuthorizedEditorUsersRouteImport } from './routes/_authorized/_editor/users'
import { Route as AuthorizedAdminFormEditRouteImport } from './routes/_authorized/_admin/form-edit'
import { Route as AuthorizedOfficesOfficeIdRouteRouteImport } from './routes/_authorized/offices/$officeId/route'
import { Route as AuthorizedEditorCompaniesRouteRouteImport } from './routes/_authorized/_editor/companies/route'
import { Route as AuthorizedEditorCompaniesIndexRouteImport } from './routes/_authorized/_editor/companies/index'
import { Route as UnauthorizedUserSignUpTokenRouteImport } from './routes/_unauthorized/_user/sign-up.$token'
import { Route as UnauthorizedUserResetPasswordTokenRouteImport } from './routes/_unauthorized/_user/reset-password.$token'
import { Route as UnauthorizedCompanySignUpCompanyRouteImport } from './routes/_unauthorized/_company/sign-up.company'
import { Route as AuthorizedCompanyAdminCompaniesCompanyIdRouteRouteImport } from './routes/_authorized/_companyAdmin/companies/$companyId/route'
import { Route as AuthorizedCompanyAdminCompaniesCompanyIdIndexRouteImport } from './routes/_authorized/_companyAdmin/companies/$companyId/index'
import { Route as AuthorizedCompanyAdminCompaniesCompanyIdUsersRouteImport } from './routes/_authorized/_companyAdmin/companies/$companyId/users'
import { Route as AuthorizedCompanyAdminCompaniesCompanyIdLogsRouteImport } from './routes/_authorized/_companyAdmin/companies/$companyId/logs'

const AuthorizedRouteRoute = AuthorizedRouteRouteImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedProfileRoute = AuthorizedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)
const AuthorizedFeedbacksRoute = AuthorizedFeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)
const AuthorizedChatsRoute = AuthorizedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)
const UnauthorizedUserRouteRoute = UnauthorizedUserRouteRouteImport.update({
  id: '/_unauthorized/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedCompanyRouteRoute =
  UnauthorizedCompanyRouteRouteImport.update({
    id: '/_unauthorized/_company',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthorizedOfficesRouteRoute = AuthorizedOfficesRouteRouteImport.update({
  id: '/offices',
  path: '/offices',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)
const AuthorizedEditorRouteRoute = AuthorizedEditorRouteRouteImport.update({
  id: '/_editor',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)
const AuthorizedCompanyAdminRouteRoute =
  AuthorizedCompanyAdminRouteRouteImport.update({
    id: '/_companyAdmin',
    getParentRoute: () => AuthorizedRouteRoute,
  } as any)
const AuthorizedAdminRouteRoute = AuthorizedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)
const AuthorizedOfficesIndexRoute = AuthorizedOfficesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthorizedOfficesRouteRoute,
} as any)
const UnauthorizedUserLoginRoute = UnauthorizedUserLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UnauthorizedUserRouteRoute,
} as any)
const UnauthorizedUserForgotPasswordRoute =
  UnauthorizedUserForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => UnauthorizedUserRouteRoute,
  } as any)
const UnauthorizedUserCheckEmailRoute =
  UnauthorizedUserCheckEmailRouteImport.update({
    id: '/check-email',
    path: '/check-email',
    getParentRoute: () => UnauthorizedUserRouteRoute,
  } as any)
const AuthorizedEditorUsersRoute = AuthorizedEditorUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthorizedEditorRouteRoute,
} as any)
const AuthorizedAdminFormEditRoute = AuthorizedAdminFormEditRouteImport.update({
  id: '/form-edit',
  path: '/form-edit',
  getParentRoute: () => AuthorizedAdminRouteRoute,
} as any)
const AuthorizedOfficesOfficeIdRouteRoute =
  AuthorizedOfficesOfficeIdRouteRouteImport.update({
    id: '/$officeId',
    path: '/$officeId',
    getParentRoute: () => AuthorizedOfficesRouteRoute,
  } as any)
const AuthorizedEditorCompaniesRouteRoute =
  AuthorizedEditorCompaniesRouteRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthorizedEditorRouteRoute,
  } as any)
const AuthorizedEditorCompaniesIndexRoute =
  AuthorizedEditorCompaniesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthorizedEditorCompaniesRouteRoute,
  } as any)
const UnauthorizedUserSignUpTokenRoute =
  UnauthorizedUserSignUpTokenRouteImport.update({
    id: '/sign-up/$token',
    path: '/sign-up/$token',
    getParentRoute: () => UnauthorizedUserRouteRoute,
  } as any)
const UnauthorizedUserResetPasswordTokenRoute =
  UnauthorizedUserResetPasswordTokenRouteImport.update({
    id: '/reset-password/$token',
    path: '/reset-password/$token',
    getParentRoute: () => UnauthorizedUserRouteRoute,
  } as any)
const UnauthorizedCompanySignUpCompanyRoute =
  UnauthorizedCompanySignUpCompanyRouteImport.update({
    id: '/sign-up/company',
    path: '/sign-up/company',
    getParentRoute: () => UnauthorizedCompanyRouteRoute,
  } as any)
const AuthorizedCompanyAdminCompaniesCompanyIdRouteRoute =
  AuthorizedCompanyAdminCompaniesCompanyIdRouteRouteImport.update({
    id: '/companies/$companyId',
    path: '/companies/$companyId',
    getParentRoute: () => AuthorizedCompanyAdminRouteRoute,
  } as any)
const AuthorizedCompanyAdminCompaniesCompanyIdIndexRoute =
  AuthorizedCompanyAdminCompaniesCompanyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthorizedCompanyAdminCompaniesCompanyIdRouteRoute,
  } as any)
const AuthorizedCompanyAdminCompaniesCompanyIdUsersRoute =
  AuthorizedCompanyAdminCompaniesCompanyIdUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthorizedCompanyAdminCompaniesCompanyIdRouteRoute,
  } as any)
const AuthorizedCompanyAdminCompaniesCompanyIdLogsRoute =
  AuthorizedCompanyAdminCompaniesCompanyIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthorizedCompanyAdminCompaniesCompanyIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/offices': typeof AuthorizedOfficesRouteRouteWithChildren
  '/chats': typeof AuthorizedChatsRoute
  '/feedbacks': typeof AuthorizedFeedbacksRoute
  '/profile': typeof AuthorizedProfileRoute
  '/companies': typeof AuthorizedEditorCompaniesRouteRouteWithChildren
  '/offices/$officeId': typeof AuthorizedOfficesOfficeIdRouteRoute
  '/form-edit': typeof AuthorizedAdminFormEditRoute
  '/users': typeof AuthorizedEditorUsersRoute
  '/check-email': typeof UnauthorizedUserCheckEmailRoute
  '/forgot-password': typeof UnauthorizedUserForgotPasswordRoute
  '/login': typeof UnauthorizedUserLoginRoute
  '/offices/': typeof AuthorizedOfficesIndexRoute
  '/companies/$companyId': typeof AuthorizedCompanyAdminCompaniesCompanyIdRouteRouteWithChildren
  '/sign-up/company': typeof UnauthorizedCompanySignUpCompanyRoute
  '/reset-password/$token': typeof UnauthorizedUserResetPasswordTokenRoute
  '/sign-up/$token': typeof UnauthorizedUserSignUpTokenRoute
  '/companies/': typeof AuthorizedEditorCompaniesIndexRoute
  '/companies/$companyId/logs': typeof AuthorizedCompanyAdminCompaniesCompanyIdLogsRoute
  '/companies/$companyId/users': typeof AuthorizedCompanyAdminCompaniesCompanyIdUsersRoute
  '/companies/$companyId/': typeof AuthorizedCompanyAdminCompaniesCompanyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats': typeof AuthorizedChatsRoute
  '/feedbacks': typeof AuthorizedFeedbacksRoute
  '/profile': typeof AuthorizedProfileRoute
  '/offices/$officeId': typeof AuthorizedOfficesOfficeIdRouteRoute
  '/form-edit': typeof AuthorizedAdminFormEditRoute
  '/users': typeof AuthorizedEditorUsersRoute
  '/check-email': typeof UnauthorizedUserCheckEmailRoute
  '/forgot-password': typeof UnauthorizedUserForgotPasswordRoute
  '/login': typeof UnauthorizedUserLoginRoute
  '/offices': typeof AuthorizedOfficesIndexRoute
  '/sign-up/company': typeof UnauthorizedCompanySignUpCompanyRoute
  '/reset-password/$token': typeof UnauthorizedUserResetPasswordTokenRoute
  '/sign-up/$token': typeof UnauthorizedUserSignUpTokenRoute
  '/companies': typeof AuthorizedEditorCompaniesIndexRoute
  '/companies/$companyId/logs': typeof AuthorizedCompanyAdminCompaniesCompanyIdLogsRoute
  '/companies/$companyId/users': typeof AuthorizedCompanyAdminCompaniesCompanyIdUsersRoute
  '/companies/$companyId': typeof AuthorizedCompanyAdminCompaniesCompanyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authorized': typeof AuthorizedRouteRouteWithChildren
  '/_authorized/_admin': typeof AuthorizedAdminRouteRouteWithChildren
  '/_authorized/_companyAdmin': typeof AuthorizedCompanyAdminRouteRouteWithChildren
  '/_authorized/_editor': typeof AuthorizedEditorRouteRouteWithChildren
  '/_authorized/offices': typeof AuthorizedOfficesRouteRouteWithChildren
  '/_unauthorized/_company': typeof UnauthorizedCompanyRouteRouteWithChildren
  '/_unauthorized/_user': typeof UnauthorizedUserRouteRouteWithChildren
  '/_authorized/chats': typeof AuthorizedChatsRoute
  '/_authorized/feedbacks': typeof AuthorizedFeedbacksRoute
  '/_authorized/profile': typeof AuthorizedProfileRoute
  '/_authorized/_editor/companies': typeof AuthorizedEditorCompaniesRouteRouteWithChildren
  '/_authorized/offices/$officeId': typeof AuthorizedOfficesOfficeIdRouteRoute
  '/_authorized/_admin/form-edit': typeof AuthorizedAdminFormEditRoute
  '/_authorized/_editor/users': typeof AuthorizedEditorUsersRoute
  '/_unauthorized/_user/check-email': typeof UnauthorizedUserCheckEmailRoute
  '/_unauthorized/_user/forgot-password': typeof UnauthorizedUserForgotPasswordRoute
  '/_unauthorized/_user/login': typeof UnauthorizedUserLoginRoute
  '/_authorized/offices/': typeof AuthorizedOfficesIndexRoute
  '/_authorized/_companyAdmin/companies/$companyId': typeof AuthorizedCompanyAdminCompaniesCompanyIdRouteRouteWithChildren
  '/_unauthorized/_company/sign-up/company': typeof UnauthorizedCompanySignUpCompanyRoute
  '/_unauthorized/_user/reset-password/$token': typeof UnauthorizedUserResetPasswordTokenRoute
  '/_unauthorized/_user/sign-up/$token': typeof UnauthorizedUserSignUpTokenRoute
  '/_authorized/_editor/companies/': typeof AuthorizedEditorCompaniesIndexRoute
  '/_authorized/_companyAdmin/companies/$companyId/logs': typeof AuthorizedCompanyAdminCompaniesCompanyIdLogsRoute
  '/_authorized/_companyAdmin/companies/$companyId/users': typeof AuthorizedCompanyAdminCompaniesCompanyIdUsersRoute
  '/_authorized/_companyAdmin/companies/$companyId/': typeof AuthorizedCompanyAdminCompaniesCompanyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/offices'
    | '/chats'
    | '/feedbacks'
    | '/profile'
    | '/companies'
    | '/offices/$officeId'
    | '/form-edit'
    | '/users'
    | '/check-email'
    | '/forgot-password'
    | '/login'
    | '/offices/'
    | '/companies/$companyId'
    | '/sign-up/company'
    | '/reset-password/$token'
    | '/sign-up/$token'
    | '/companies/'
    | '/companies/$companyId/logs'
    | '/companies/$companyId/users'
    | '/companies/$companyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chats'
    | '/feedbacks'
    | '/profile'
    | '/offices/$officeId'
    | '/form-edit'
    | '/users'
    | '/check-email'
    | '/forgot-password'
    | '/login'
    | '/offices'
    | '/sign-up/company'
    | '/reset-password/$token'
    | '/sign-up/$token'
    | '/companies'
    | '/companies/$companyId/logs'
    | '/companies/$companyId/users'
    | '/companies/$companyId'
  id:
    | '__root__'
    | '/'
    | '/_authorized'
    | '/_authorized/_admin'
    | '/_authorized/_companyAdmin'
    | '/_authorized/_editor'
    | '/_authorized/offices'
    | '/_unauthorized/_company'
    | '/_unauthorized/_user'
    | '/_authorized/chats'
    | '/_authorized/feedbacks'
    | '/_authorized/profile'
    | '/_authorized/_editor/companies'
    | '/_authorized/offices/$officeId'
    | '/_authorized/_admin/form-edit'
    | '/_authorized/_editor/users'
    | '/_unauthorized/_user/check-email'
    | '/_unauthorized/_user/forgot-password'
    | '/_unauthorized/_user/login'
    | '/_authorized/offices/'
    | '/_authorized/_companyAdmin/companies/$companyId'
    | '/_unauthorized/_company/sign-up/company'
    | '/_unauthorized/_user/reset-password/$token'
    | '/_unauthorized/_user/sign-up/$token'
    | '/_authorized/_editor/companies/'
    | '/_authorized/_companyAdmin/companies/$companyId/logs'
    | '/_authorized/_companyAdmin/companies/$companyId/users'
    | '/_authorized/_companyAdmin/companies/$companyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorizedRouteRoute: typeof AuthorizedRouteRouteWithChildren
  UnauthorizedCompanyRouteRoute: typeof UnauthorizedCompanyRouteRouteWithChildren
  UnauthorizedUserRouteRoute: typeof UnauthorizedUserRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authorized': {
      id: '/_authorized'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthorizedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized/profile': {
      id: '/_authorized/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthorizedProfileRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_authorized/feedbacks': {
      id: '/_authorized/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof AuthorizedFeedbacksRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_authorized/chats': {
      id: '/_authorized/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthorizedChatsRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_unauthorized/_user': {
      id: '/_unauthorized/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthorizedUserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthorized/_company': {
      id: '/_unauthorized/_company'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthorizedCompanyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized/offices': {
      id: '/_authorized/offices'
      path: '/offices'
      fullPath: '/offices'
      preLoaderRoute: typeof AuthorizedOfficesRouteRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_authorized/_editor': {
      id: '/_authorized/_editor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthorizedEditorRouteRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_authorized/_companyAdmin': {
      id: '/_authorized/_companyAdmin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthorizedCompanyAdminRouteRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_authorized/_admin': {
      id: '/_authorized/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthorizedAdminRouteRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_authorized/offices/': {
      id: '/_authorized/offices/'
      path: '/'
      fullPath: '/offices/'
      preLoaderRoute: typeof AuthorizedOfficesIndexRouteImport
      parentRoute: typeof AuthorizedOfficesRouteRoute
    }
    '/_unauthorized/_user/login': {
      id: '/_unauthorized/_user/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthorizedUserLoginRouteImport
      parentRoute: typeof UnauthorizedUserRouteRoute
    }
    '/_unauthorized/_user/forgot-password': {
      id: '/_unauthorized/_user/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof UnauthorizedUserForgotPasswordRouteImport
      parentRoute: typeof UnauthorizedUserRouteRoute
    }
    '/_unauthorized/_user/check-email': {
      id: '/_unauthorized/_user/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof UnauthorizedUserCheckEmailRouteImport
      parentRoute: typeof UnauthorizedUserRouteRoute
    }
    '/_authorized/_editor/users': {
      id: '/_authorized/_editor/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthorizedEditorUsersRouteImport
      parentRoute: typeof AuthorizedEditorRouteRoute
    }
    '/_authorized/_admin/form-edit': {
      id: '/_authorized/_admin/form-edit'
      path: '/form-edit'
      fullPath: '/form-edit'
      preLoaderRoute: typeof AuthorizedAdminFormEditRouteImport
      parentRoute: typeof AuthorizedAdminRouteRoute
    }
    '/_authorized/offices/$officeId': {
      id: '/_authorized/offices/$officeId'
      path: '/$officeId'
      fullPath: '/offices/$officeId'
      preLoaderRoute: typeof AuthorizedOfficesOfficeIdRouteRouteImport
      parentRoute: typeof AuthorizedOfficesRouteRoute
    }
    '/_authorized/_editor/companies': {
      id: '/_authorized/_editor/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthorizedEditorCompaniesRouteRouteImport
      parentRoute: typeof AuthorizedEditorRouteRoute
    }
    '/_authorized/_editor/companies/': {
      id: '/_authorized/_editor/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthorizedEditorCompaniesIndexRouteImport
      parentRoute: typeof AuthorizedEditorCompaniesRouteRoute
    }
    '/_unauthorized/_user/sign-up/$token': {
      id: '/_unauthorized/_user/sign-up/$token'
      path: '/sign-up/$token'
      fullPath: '/sign-up/$token'
      preLoaderRoute: typeof UnauthorizedUserSignUpTokenRouteImport
      parentRoute: typeof UnauthorizedUserRouteRoute
    }
    '/_unauthorized/_user/reset-password/$token': {
      id: '/_unauthorized/_user/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof UnauthorizedUserResetPasswordTokenRouteImport
      parentRoute: typeof UnauthorizedUserRouteRoute
    }
    '/_unauthorized/_company/sign-up/company': {
      id: '/_unauthorized/_company/sign-up/company'
      path: '/sign-up/company'
      fullPath: '/sign-up/company'
      preLoaderRoute: typeof UnauthorizedCompanySignUpCompanyRouteImport
      parentRoute: typeof UnauthorizedCompanyRouteRoute
    }
    '/_authorized/_companyAdmin/companies/$companyId': {
      id: '/_authorized/_companyAdmin/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AuthorizedCompanyAdminCompaniesCompanyIdRouteRouteImport
      parentRoute: typeof AuthorizedCompanyAdminRouteRoute
    }
    '/_authorized/_companyAdmin/companies/$companyId/': {
      id: '/_authorized/_companyAdmin/companies/$companyId/'
      path: '/'
      fullPath: '/companies/$companyId/'
      preLoaderRoute: typeof AuthorizedCompanyAdminCompaniesCompanyIdIndexRouteImport
      parentRoute: typeof AuthorizedCompanyAdminCompaniesCompanyIdRouteRoute
    }
    '/_authorized/_companyAdmin/companies/$companyId/users': {
      id: '/_authorized/_companyAdmin/companies/$companyId/users'
      path: '/users'
      fullPath: '/companies/$companyId/users'
      preLoaderRoute: typeof AuthorizedCompanyAdminCompaniesCompanyIdUsersRouteImport
      parentRoute: typeof AuthorizedCompanyAdminCompaniesCompanyIdRouteRoute
    }
    '/_authorized/_companyAdmin/companies/$companyId/logs': {
      id: '/_authorized/_companyAdmin/companies/$companyId/logs'
      path: '/logs'
      fullPath: '/companies/$companyId/logs'
      preLoaderRoute: typeof AuthorizedCompanyAdminCompaniesCompanyIdLogsRouteImport
      parentRoute: typeof AuthorizedCompanyAdminCompaniesCompanyIdRouteRoute
    }
  }
}

interface AuthorizedAdminRouteRouteChildren {
  AuthorizedAdminFormEditRoute: typeof AuthorizedAdminFormEditRoute
}

const AuthorizedAdminRouteRouteChildren: AuthorizedAdminRouteRouteChildren = {
  AuthorizedAdminFormEditRoute: AuthorizedAdminFormEditRoute,
}

const AuthorizedAdminRouteRouteWithChildren =
  AuthorizedAdminRouteRoute._addFileChildren(AuthorizedAdminRouteRouteChildren)

interface AuthorizedCompanyAdminCompaniesCompanyIdRouteRouteChildren {
  AuthorizedCompanyAdminCompaniesCompanyIdLogsRoute: typeof AuthorizedCompanyAdminCompaniesCompanyIdLogsRoute
  AuthorizedCompanyAdminCompaniesCompanyIdUsersRoute: typeof AuthorizedCompanyAdminCompaniesCompanyIdUsersRoute
  AuthorizedCompanyAdminCompaniesCompanyIdIndexRoute: typeof AuthorizedCompanyAdminCompaniesCompanyIdIndexRoute
}

const AuthorizedCompanyAdminCompaniesCompanyIdRouteRouteChildren: AuthorizedCompanyAdminCompaniesCompanyIdRouteRouteChildren =
  {
    AuthorizedCompanyAdminCompaniesCompanyIdLogsRoute:
      AuthorizedCompanyAdminCompaniesCompanyIdLogsRoute,
    AuthorizedCompanyAdminCompaniesCompanyIdUsersRoute:
      AuthorizedCompanyAdminCompaniesCompanyIdUsersRoute,
    AuthorizedCompanyAdminCompaniesCompanyIdIndexRoute:
      AuthorizedCompanyAdminCompaniesCompanyIdIndexRoute,
  }

const AuthorizedCompanyAdminCompaniesCompanyIdRouteRouteWithChildren =
  AuthorizedCompanyAdminCompaniesCompanyIdRouteRoute._addFileChildren(
    AuthorizedCompanyAdminCompaniesCompanyIdRouteRouteChildren,
  )

interface AuthorizedCompanyAdminRouteRouteChildren {
  AuthorizedCompanyAdminCompaniesCompanyIdRouteRoute: typeof AuthorizedCompanyAdminCompaniesCompanyIdRouteRouteWithChildren
}

const AuthorizedCompanyAdminRouteRouteChildren: AuthorizedCompanyAdminRouteRouteChildren =
  {
    AuthorizedCompanyAdminCompaniesCompanyIdRouteRoute:
      AuthorizedCompanyAdminCompaniesCompanyIdRouteRouteWithChildren,
  }

const AuthorizedCompanyAdminRouteRouteWithChildren =
  AuthorizedCompanyAdminRouteRoute._addFileChildren(
    AuthorizedCompanyAdminRouteRouteChildren,
  )

interface AuthorizedEditorCompaniesRouteRouteChildren {
  AuthorizedEditorCompaniesIndexRoute: typeof AuthorizedEditorCompaniesIndexRoute
}

const AuthorizedEditorCompaniesRouteRouteChildren: AuthorizedEditorCompaniesRouteRouteChildren =
  {
    AuthorizedEditorCompaniesIndexRoute: AuthorizedEditorCompaniesIndexRoute,
  }

const AuthorizedEditorCompaniesRouteRouteWithChildren =
  AuthorizedEditorCompaniesRouteRoute._addFileChildren(
    AuthorizedEditorCompaniesRouteRouteChildren,
  )

interface AuthorizedEditorRouteRouteChildren {
  AuthorizedEditorCompaniesRouteRoute: typeof AuthorizedEditorCompaniesRouteRouteWithChildren
  AuthorizedEditorUsersRoute: typeof AuthorizedEditorUsersRoute
}

const AuthorizedEditorRouteRouteChildren: AuthorizedEditorRouteRouteChildren = {
  AuthorizedEditorCompaniesRouteRoute:
    AuthorizedEditorCompaniesRouteRouteWithChildren,
  AuthorizedEditorUsersRoute: AuthorizedEditorUsersRoute,
}

const AuthorizedEditorRouteRouteWithChildren =
  AuthorizedEditorRouteRoute._addFileChildren(
    AuthorizedEditorRouteRouteChildren,
  )

interface AuthorizedOfficesRouteRouteChildren {
  AuthorizedOfficesOfficeIdRouteRoute: typeof AuthorizedOfficesOfficeIdRouteRoute
  AuthorizedOfficesIndexRoute: typeof AuthorizedOfficesIndexRoute
}

const AuthorizedOfficesRouteRouteChildren: AuthorizedOfficesRouteRouteChildren =
  {
    AuthorizedOfficesOfficeIdRouteRoute: AuthorizedOfficesOfficeIdRouteRoute,
    AuthorizedOfficesIndexRoute: AuthorizedOfficesIndexRoute,
  }

const AuthorizedOfficesRouteRouteWithChildren =
  AuthorizedOfficesRouteRoute._addFileChildren(
    AuthorizedOfficesRouteRouteChildren,
  )

interface AuthorizedRouteRouteChildren {
  AuthorizedAdminRouteRoute: typeof AuthorizedAdminRouteRouteWithChildren
  AuthorizedCompanyAdminRouteRoute: typeof AuthorizedCompanyAdminRouteRouteWithChildren
  AuthorizedEditorRouteRoute: typeof AuthorizedEditorRouteRouteWithChildren
  AuthorizedOfficesRouteRoute: typeof AuthorizedOfficesRouteRouteWithChildren
  AuthorizedChatsRoute: typeof AuthorizedChatsRoute
  AuthorizedFeedbacksRoute: typeof AuthorizedFeedbacksRoute
  AuthorizedProfileRoute: typeof AuthorizedProfileRoute
}

const AuthorizedRouteRouteChildren: AuthorizedRouteRouteChildren = {
  AuthorizedAdminRouteRoute: AuthorizedAdminRouteRouteWithChildren,
  AuthorizedCompanyAdminRouteRoute:
    AuthorizedCompanyAdminRouteRouteWithChildren,
  AuthorizedEditorRouteRoute: AuthorizedEditorRouteRouteWithChildren,
  AuthorizedOfficesRouteRoute: AuthorizedOfficesRouteRouteWithChildren,
  AuthorizedChatsRoute: AuthorizedChatsRoute,
  AuthorizedFeedbacksRoute: AuthorizedFeedbacksRoute,
  AuthorizedProfileRoute: AuthorizedProfileRoute,
}

const AuthorizedRouteRouteWithChildren = AuthorizedRouteRoute._addFileChildren(
  AuthorizedRouteRouteChildren,
)

interface UnauthorizedCompanyRouteRouteChildren {
  UnauthorizedCompanySignUpCompanyRoute: typeof UnauthorizedCompanySignUpCompanyRoute
}

const UnauthorizedCompanyRouteRouteChildren: UnauthorizedCompanyRouteRouteChildren =
  {
    UnauthorizedCompanySignUpCompanyRoute:
      UnauthorizedCompanySignUpCompanyRoute,
  }

const UnauthorizedCompanyRouteRouteWithChildren =
  UnauthorizedCompanyRouteRoute._addFileChildren(
    UnauthorizedCompanyRouteRouteChildren,
  )

interface UnauthorizedUserRouteRouteChildren {
  UnauthorizedUserCheckEmailRoute: typeof UnauthorizedUserCheckEmailRoute
  UnauthorizedUserForgotPasswordRoute: typeof UnauthorizedUserForgotPasswordRoute
  UnauthorizedUserLoginRoute: typeof UnauthorizedUserLoginRoute
  UnauthorizedUserResetPasswordTokenRoute: typeof UnauthorizedUserResetPasswordTokenRoute
  UnauthorizedUserSignUpTokenRoute: typeof UnauthorizedUserSignUpTokenRoute
}

const UnauthorizedUserRouteRouteChildren: UnauthorizedUserRouteRouteChildren = {
  UnauthorizedUserCheckEmailRoute: UnauthorizedUserCheckEmailRoute,
  UnauthorizedUserForgotPasswordRoute: UnauthorizedUserForgotPasswordRoute,
  UnauthorizedUserLoginRoute: UnauthorizedUserLoginRoute,
  UnauthorizedUserResetPasswordTokenRoute:
    UnauthorizedUserResetPasswordTokenRoute,
  UnauthorizedUserSignUpTokenRoute: UnauthorizedUserSignUpTokenRoute,
}

const UnauthorizedUserRouteRouteWithChildren =
  UnauthorizedUserRouteRoute._addFileChildren(
    UnauthorizedUserRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorizedRouteRoute: AuthorizedRouteRouteWithChildren,
  UnauthorizedCompanyRouteRoute: UnauthorizedCompanyRouteRouteWithChildren,
  UnauthorizedUserRouteRoute: UnauthorizedUserRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
