/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteRouteImport } from './routes/_unauthorized/route'
import { Route as AuthorizedRouteRouteImport } from './routes/_authorized/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnauthorizedLoginRouteImport } from './routes/_unauthorized/login'
import { Route as UnauthorizedForgotPasswordRouteImport } from './routes/_unauthorized/forgot-password'
import { Route as UnauthorizedCheckEmailRouteImport } from './routes/_unauthorized/check-email'
import { Route as AuthorizedProfileRouteImport } from './routes/_authorized/profile'
import { Route as AuthorizedChatsRouteImport } from './routes/_authorized/chats'
import { Route as AuthorizedEditorRouteRouteImport } from './routes/_authorized/_editor/route'
import { Route as AuthorizedCompanyAdminRouteRouteImport } from './routes/_authorized/_companyAdmin/route'
import { Route as AuthorizedAdminRouteRouteImport } from './routes/_authorized/_admin/route'
import { Route as UnauthorizedSignUpTokenRouteImport } from './routes/_unauthorized/sign-up.$token'
import { Route as UnauthorizedResetPasswordTokenRouteImport } from './routes/_unauthorized/reset-password.$token'
import { Route as AuthorizedEditorUsersRouteImport } from './routes/_authorized/_editor/users'
import { Route as AuthorizedCompanyAdminCompanyRouteImport } from './routes/_authorized/_companyAdmin/company'
import { Route as AuthorizedEditorCompaniesRouteRouteImport } from './routes/_authorized/_editor/companies/route'
import { Route as AuthorizedEditorCompaniesIndexRouteImport } from './routes/_authorized/_editor/companies/index'
import { Route as AuthorizedEditorCompaniesCompanyIdRouteRouteImport } from './routes/_authorized/_editor/companies/$companyId/route'

const UnauthorizedRouteRoute = UnauthorizedRouteRouteImport.update({
  id: '/_unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedRouteRoute = AuthorizedRouteRouteImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedLoginRoute = UnauthorizedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UnauthorizedRouteRoute,
} as any)
const UnauthorizedForgotPasswordRoute =
  UnauthorizedForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => UnauthorizedRouteRoute,
  } as any)
const UnauthorizedCheckEmailRoute = UnauthorizedCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => UnauthorizedRouteRoute,
} as any)
const AuthorizedProfileRoute = AuthorizedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)
const AuthorizedChatsRoute = AuthorizedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)
const AuthorizedEditorRouteRoute = AuthorizedEditorRouteRouteImport.update({
  id: '/_editor',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)
const AuthorizedCompanyAdminRouteRoute =
  AuthorizedCompanyAdminRouteRouteImport.update({
    id: '/_companyAdmin',
    getParentRoute: () => AuthorizedRouteRoute,
  } as any)
const AuthorizedAdminRouteRoute = AuthorizedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)
const UnauthorizedSignUpTokenRoute = UnauthorizedSignUpTokenRouteImport.update({
  id: '/sign-up/$token',
  path: '/sign-up/$token',
  getParentRoute: () => UnauthorizedRouteRoute,
} as any)
const UnauthorizedResetPasswordTokenRoute =
  UnauthorizedResetPasswordTokenRouteImport.update({
    id: '/reset-password/$token',
    path: '/reset-password/$token',
    getParentRoute: () => UnauthorizedRouteRoute,
  } as any)
const AuthorizedEditorUsersRoute = AuthorizedEditorUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthorizedEditorRouteRoute,
} as any)
const AuthorizedCompanyAdminCompanyRoute =
  AuthorizedCompanyAdminCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthorizedCompanyAdminRouteRoute,
  } as any)
const AuthorizedEditorCompaniesRouteRoute =
  AuthorizedEditorCompaniesRouteRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthorizedEditorRouteRoute,
  } as any)
const AuthorizedEditorCompaniesIndexRoute =
  AuthorizedEditorCompaniesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthorizedEditorCompaniesRouteRoute,
  } as any)
const AuthorizedEditorCompaniesCompanyIdRouteRoute =
  AuthorizedEditorCompaniesCompanyIdRouteRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => AuthorizedEditorCompaniesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof AuthorizedChatsRoute
  '/profile': typeof AuthorizedProfileRoute
  '/check-email': typeof UnauthorizedCheckEmailRoute
  '/forgot-password': typeof UnauthorizedForgotPasswordRoute
  '/login': typeof UnauthorizedLoginRoute
  '/companies': typeof AuthorizedEditorCompaniesRouteRouteWithChildren
  '/company': typeof AuthorizedCompanyAdminCompanyRoute
  '/users': typeof AuthorizedEditorUsersRoute
  '/reset-password/$token': typeof UnauthorizedResetPasswordTokenRoute
  '/sign-up/$token': typeof UnauthorizedSignUpTokenRoute
  '/companies/$companyId': typeof AuthorizedEditorCompaniesCompanyIdRouteRoute
  '/companies/': typeof AuthorizedEditorCompaniesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats': typeof AuthorizedChatsRoute
  '/profile': typeof AuthorizedProfileRoute
  '/check-email': typeof UnauthorizedCheckEmailRoute
  '/forgot-password': typeof UnauthorizedForgotPasswordRoute
  '/login': typeof UnauthorizedLoginRoute
  '/company': typeof AuthorizedCompanyAdminCompanyRoute
  '/users': typeof AuthorizedEditorUsersRoute
  '/reset-password/$token': typeof UnauthorizedResetPasswordTokenRoute
  '/sign-up/$token': typeof UnauthorizedSignUpTokenRoute
  '/companies/$companyId': typeof AuthorizedEditorCompaniesCompanyIdRouteRoute
  '/companies': typeof AuthorizedEditorCompaniesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authorized': typeof AuthorizedRouteRouteWithChildren
  '/_unauthorized': typeof UnauthorizedRouteRouteWithChildren
  '/_authorized/_admin': typeof AuthorizedAdminRouteRoute
  '/_authorized/_companyAdmin': typeof AuthorizedCompanyAdminRouteRouteWithChildren
  '/_authorized/_editor': typeof AuthorizedEditorRouteRouteWithChildren
  '/_authorized/chats': typeof AuthorizedChatsRoute
  '/_authorized/profile': typeof AuthorizedProfileRoute
  '/_unauthorized/check-email': typeof UnauthorizedCheckEmailRoute
  '/_unauthorized/forgot-password': typeof UnauthorizedForgotPasswordRoute
  '/_unauthorized/login': typeof UnauthorizedLoginRoute
  '/_authorized/_editor/companies': typeof AuthorizedEditorCompaniesRouteRouteWithChildren
  '/_authorized/_companyAdmin/company': typeof AuthorizedCompanyAdminCompanyRoute
  '/_authorized/_editor/users': typeof AuthorizedEditorUsersRoute
  '/_unauthorized/reset-password/$token': typeof UnauthorizedResetPasswordTokenRoute
  '/_unauthorized/sign-up/$token': typeof UnauthorizedSignUpTokenRoute
  '/_authorized/_editor/companies/$companyId': typeof AuthorizedEditorCompaniesCompanyIdRouteRoute
  '/_authorized/_editor/companies/': typeof AuthorizedEditorCompaniesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chats'
    | '/profile'
    | '/check-email'
    | '/forgot-password'
    | '/login'
    | '/companies'
    | '/company'
    | '/users'
    | '/reset-password/$token'
    | '/sign-up/$token'
    | '/companies/$companyId'
    | '/companies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chats'
    | '/profile'
    | '/check-email'
    | '/forgot-password'
    | '/login'
    | '/company'
    | '/users'
    | '/reset-password/$token'
    | '/sign-up/$token'
    | '/companies/$companyId'
    | '/companies'
  id:
    | '__root__'
    | '/'
    | '/_authorized'
    | '/_unauthorized'
    | '/_authorized/_admin'
    | '/_authorized/_companyAdmin'
    | '/_authorized/_editor'
    | '/_authorized/chats'
    | '/_authorized/profile'
    | '/_unauthorized/check-email'
    | '/_unauthorized/forgot-password'
    | '/_unauthorized/login'
    | '/_authorized/_editor/companies'
    | '/_authorized/_companyAdmin/company'
    | '/_authorized/_editor/users'
    | '/_unauthorized/reset-password/$token'
    | '/_unauthorized/sign-up/$token'
    | '/_authorized/_editor/companies/$companyId'
    | '/_authorized/_editor/companies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorizedRouteRoute: typeof AuthorizedRouteRouteWithChildren
  UnauthorizedRouteRoute: typeof UnauthorizedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthorized': {
      id: '/_unauthorized'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthorizedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized': {
      id: '/_authorized'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthorizedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthorized/login': {
      id: '/_unauthorized/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthorizedLoginRouteImport
      parentRoute: typeof UnauthorizedRouteRoute
    }
    '/_unauthorized/forgot-password': {
      id: '/_unauthorized/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof UnauthorizedForgotPasswordRouteImport
      parentRoute: typeof UnauthorizedRouteRoute
    }
    '/_unauthorized/check-email': {
      id: '/_unauthorized/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof UnauthorizedCheckEmailRouteImport
      parentRoute: typeof UnauthorizedRouteRoute
    }
    '/_authorized/profile': {
      id: '/_authorized/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthorizedProfileRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_authorized/chats': {
      id: '/_authorized/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthorizedChatsRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_authorized/_editor': {
      id: '/_authorized/_editor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthorizedEditorRouteRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_authorized/_companyAdmin': {
      id: '/_authorized/_companyAdmin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthorizedCompanyAdminRouteRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_authorized/_admin': {
      id: '/_authorized/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthorizedAdminRouteRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_unauthorized/sign-up/$token': {
      id: '/_unauthorized/sign-up/$token'
      path: '/sign-up/$token'
      fullPath: '/sign-up/$token'
      preLoaderRoute: typeof UnauthorizedSignUpTokenRouteImport
      parentRoute: typeof UnauthorizedRouteRoute
    }
    '/_unauthorized/reset-password/$token': {
      id: '/_unauthorized/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof UnauthorizedResetPasswordTokenRouteImport
      parentRoute: typeof UnauthorizedRouteRoute
    }
    '/_authorized/_editor/users': {
      id: '/_authorized/_editor/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthorizedEditorUsersRouteImport
      parentRoute: typeof AuthorizedEditorRouteRoute
    }
    '/_authorized/_companyAdmin/company': {
      id: '/_authorized/_companyAdmin/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthorizedCompanyAdminCompanyRouteImport
      parentRoute: typeof AuthorizedCompanyAdminRouteRoute
    }
    '/_authorized/_editor/companies': {
      id: '/_authorized/_editor/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthorizedEditorCompaniesRouteRouteImport
      parentRoute: typeof AuthorizedEditorRouteRoute
    }
    '/_authorized/_editor/companies/': {
      id: '/_authorized/_editor/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthorizedEditorCompaniesIndexRouteImport
      parentRoute: typeof AuthorizedEditorCompaniesRouteRoute
    }
    '/_authorized/_editor/companies/$companyId': {
      id: '/_authorized/_editor/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AuthorizedEditorCompaniesCompanyIdRouteRouteImport
      parentRoute: typeof AuthorizedEditorCompaniesRouteRoute
    }
  }
}

interface AuthorizedCompanyAdminRouteRouteChildren {
  AuthorizedCompanyAdminCompanyRoute: typeof AuthorizedCompanyAdminCompanyRoute
}

const AuthorizedCompanyAdminRouteRouteChildren: AuthorizedCompanyAdminRouteRouteChildren =
  {
    AuthorizedCompanyAdminCompanyRoute: AuthorizedCompanyAdminCompanyRoute,
  }

const AuthorizedCompanyAdminRouteRouteWithChildren =
  AuthorizedCompanyAdminRouteRoute._addFileChildren(
    AuthorizedCompanyAdminRouteRouteChildren,
  )

interface AuthorizedEditorCompaniesRouteRouteChildren {
  AuthorizedEditorCompaniesCompanyIdRouteRoute: typeof AuthorizedEditorCompaniesCompanyIdRouteRoute
  AuthorizedEditorCompaniesIndexRoute: typeof AuthorizedEditorCompaniesIndexRoute
}

const AuthorizedEditorCompaniesRouteRouteChildren: AuthorizedEditorCompaniesRouteRouteChildren =
  {
    AuthorizedEditorCompaniesCompanyIdRouteRoute:
      AuthorizedEditorCompaniesCompanyIdRouteRoute,
    AuthorizedEditorCompaniesIndexRoute: AuthorizedEditorCompaniesIndexRoute,
  }

const AuthorizedEditorCompaniesRouteRouteWithChildren =
  AuthorizedEditorCompaniesRouteRoute._addFileChildren(
    AuthorizedEditorCompaniesRouteRouteChildren,
  )

interface AuthorizedEditorRouteRouteChildren {
  AuthorizedEditorCompaniesRouteRoute: typeof AuthorizedEditorCompaniesRouteRouteWithChildren
  AuthorizedEditorUsersRoute: typeof AuthorizedEditorUsersRoute
}

const AuthorizedEditorRouteRouteChildren: AuthorizedEditorRouteRouteChildren = {
  AuthorizedEditorCompaniesRouteRoute:
    AuthorizedEditorCompaniesRouteRouteWithChildren,
  AuthorizedEditorUsersRoute: AuthorizedEditorUsersRoute,
}

const AuthorizedEditorRouteRouteWithChildren =
  AuthorizedEditorRouteRoute._addFileChildren(
    AuthorizedEditorRouteRouteChildren,
  )

interface AuthorizedRouteRouteChildren {
  AuthorizedAdminRouteRoute: typeof AuthorizedAdminRouteRoute
  AuthorizedCompanyAdminRouteRoute: typeof AuthorizedCompanyAdminRouteRouteWithChildren
  AuthorizedEditorRouteRoute: typeof AuthorizedEditorRouteRouteWithChildren
  AuthorizedChatsRoute: typeof AuthorizedChatsRoute
  AuthorizedProfileRoute: typeof AuthorizedProfileRoute
}

const AuthorizedRouteRouteChildren: AuthorizedRouteRouteChildren = {
  AuthorizedAdminRouteRoute: AuthorizedAdminRouteRoute,
  AuthorizedCompanyAdminRouteRoute:
    AuthorizedCompanyAdminRouteRouteWithChildren,
  AuthorizedEditorRouteRoute: AuthorizedEditorRouteRouteWithChildren,
  AuthorizedChatsRoute: AuthorizedChatsRoute,
  AuthorizedProfileRoute: AuthorizedProfileRoute,
}

const AuthorizedRouteRouteWithChildren = AuthorizedRouteRoute._addFileChildren(
  AuthorizedRouteRouteChildren,
)

interface UnauthorizedRouteRouteChildren {
  UnauthorizedCheckEmailRoute: typeof UnauthorizedCheckEmailRoute
  UnauthorizedForgotPasswordRoute: typeof UnauthorizedForgotPasswordRoute
  UnauthorizedLoginRoute: typeof UnauthorizedLoginRoute
  UnauthorizedResetPasswordTokenRoute: typeof UnauthorizedResetPasswordTokenRoute
  UnauthorizedSignUpTokenRoute: typeof UnauthorizedSignUpTokenRoute
}

const UnauthorizedRouteRouteChildren: UnauthorizedRouteRouteChildren = {
  UnauthorizedCheckEmailRoute: UnauthorizedCheckEmailRoute,
  UnauthorizedForgotPasswordRoute: UnauthorizedForgotPasswordRoute,
  UnauthorizedLoginRoute: UnauthorizedLoginRoute,
  UnauthorizedResetPasswordTokenRoute: UnauthorizedResetPasswordTokenRoute,
  UnauthorizedSignUpTokenRoute: UnauthorizedSignUpTokenRoute,
}

const UnauthorizedRouteRouteWithChildren =
  UnauthorizedRouteRoute._addFileChildren(UnauthorizedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorizedRouteRoute: AuthorizedRouteRouteWithChildren,
  UnauthorizedRouteRoute: UnauthorizedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
